export const FETCH_SALE_DATA_START = 'FETCH_SALE_DATA_START';
export const FETCH_SALE_DATA_SUCCESS = 'FETCH_SALE_DATA_SUCCESS';
export const FETCH_SALE_DATA_FAIL = 'FETCH_SALE_DATA_FAIL';

export const SAVE_SALE_DATA_START = 'SAVE_SALE_DATA_START';
export const SAVE_SALE_DATA_SUCCESS = 'SAVE_SALE_DATA_SUCCESS';
export const SAVE_SALE_DATA_FAIL = 'SAVE_SALE_DATA_FAIL';

export const FETCH_INVENTORY_DATA_START = 'FETCH_INVENTORY_DATA_START';
export const FETCH_INVENTORY_DATA_SUCCESS = 'FETCH_INVENTORY_DATA_SUCCESS';
export const FETCH_INVENTORY_DATA_FAIL = 'FETCH_INVENTORY_DATA_FAIL';

export const SAVE_INVENTORY_DATA_START = 'SAVE_INVENTORY_DATA_START';
export const SAVE_INVENTORY_DATA_SUCCESS = 'SAVE_INVENTORY_DATA_SUCCESS';
export const SAVE_INVENTORY_DATA_FAIL = 'SAVE_INVENTORY_DATA_FAIL';