export const FETCH_OVERVIEW_DATA_START = 'FETCH_OVERVIEW_DATA_START';
export const FETCH_OVERVIEW_DATA_SUCCESS = 'FETCH_OVERVIEW_DATA_SUCCESS';
export const FETCH_OVERVIEW_DATA_FAIL = 'FETCH_OVERVIEW_DATA_FAIL';

export const FETCH_INVENTORY_DATA_START = 'FETCH_INVENTORY_DATA_START';
export const FETCH_INVENTORY_DATA_SUCCESS = 'FETCH_INVENTORY_DATA_SUCCESS';
export const FETCH_INVENTORY_DATA_FAIL = 'FETCH_INVENTORY_DATA_FAIL';